config/routes.rb
Rails.application.routes.draw do

  root 'pins#index'
  
  get 'pins/name-:slug' => 'pins#show_by_name', as: 'pin_by_name'

  resources :pins
    
  get '/library/' => 'pins#index'
  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  validates_presence_of :title, :url, :slug, :text, :category_id
  validates_uniqueness_of :slug
  
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  
  def index
    @pins = Pin.all
  end
  
  def show
    @pin = Pin.find(params[:id])
  end
  
  def show_by_name
    @pin = Pin.find_by_slug(params[:slug])
    render :show
  end
  
  def new
    @pin = Pin.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coder Pinterest</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pins/index.erb
<div class="header">
  <h1>Learning to Code</h1>
  <h3>A Collection of Ruby on Rails Resources for Beginners</h3>
</div>
<hr/>
<div class="pins">
  <% @pins.each_slice(3) do |row| %>
    <div class="row">
      <% row.each do |pin| %>      
        <div class="pin-container col-md-4">
          <div class="pin">
            <div class="pin-header row">
				<div class="logo-thumbnail col-xs-3">
					<% if "#{pin.category_id}" == "rails"%>
						<%= image_tag('rails-logo-thumbnail.png') %>
					<% elsif "#{pin.category_id}" == "ruby" %>
						<%= image_tag('ruby-logo-thumbnail.png')%>
					<% end %>
				</div>
				<div class="pin-title col-xs-9">
              <h4>
				<%= link_to "#{pin.title}", pin_by_name_path(slug: pin.slug), html_options = {target: "_blank", class: "url"} %>
              </h4>
              <a class="url" href="<%= "#{pin.url}" %>" target="_blank">
                <%= "#{pin.url.truncate(30)}" %>
              </a>
            </div>
		</div>
            <hr/>
            <p class="text"><%= "#{pin.text}" %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<hr/>

app/views/pins/new.erb
<%= form_for @pin do |f| %>


	<div class="form-group">
		<label for="pin_title">Title</label>
		<%= f.text_field(:title, class: "form-control") %>
	</div>
	
	<div class="form-group">
		<label for="pin_category_id">Category</label>
		<%= f.collection_select(:category_id, Category.all, :id, :name) %>
	</div>
	
	<div class="form-group">
		<label for="pin_url">URL</label>
		<%= f.url_field :url, class: "form-control" %>
	</div>
	
	<div class="form-group">
		<label for"pin_text">Text</label>
		<%= f.text_area :text, class: "form-control" %>
	</div>
	
	<div class="from-group">
		<label for"pin_slug">Slug</label>
		<%= f.text_field :slug, class: "form-control" %>
	</div>
	<div class="submit-button">
		<button type="submit" class="btn btn-success">Submit</button>
	</div>

<% end %>

app/views/pins/show.erb
<div class="header">
  <h1>
	<i class="fa fa-laptop"></i>
    <%= "#{@pin.title}" %>
  </h1>
</div>

<div class="show-pin">
  <p><%= "#{@pin.text}" %></p>

  <hr/>
  <p>
    <b>Visit <%= "#{@pin.title}" %> at: </b>
    <a class="url" href="<%= "#{@pin.url}" %>" target="_blank">
      <%= "#{@pin.url}" %>
    </a>
  </p>
</div>
<br/>
<a href="/">
	<i class="fa fa-arrow-circle-left"></i>
	Back to Home
</a>